---
- hosts: kubernetes-master-nodes
  tasks:
  - name: Pulling images required for setting up a Kubernetes cluster
    shell: kubeadm config images pull

  - name: Resetting kubeadm
    shell: kubeadm reset -f
    register: output

  - name: Initializing Kubernetes cluster
    shell: kubeadm init --apiserver-advertise-address {{ad_addr}} --pod-network-cidr={{cidr_v}}
    register: output
  
  - name: "Ensure /{{inventory_dir}}/centos exist"
    file:
      path: "{{inventory_dir}}/centos"
      state: directory
      mode: 776
    delegate_to: localhost

  - name: Storing Logs and Generated token for future purpose.
    local_action: copy content={{ output.stdout }} dest="/{{inventory_dir}}/centos/{{ token_file }}"

  - name: Copying required files
    shell: |
     mkdir -p $HOME/.kube
     sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
     sudo chown $(id -u):$(id -g) $HOME/.kube/config

  - name: Install Network Add-on
    command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
