---
- hosts: kubernetes-worker-nodes
  tasks:
  - name: "Ensure /data/centos exist"
    file:
      path: "/data/centos"
      state: directory
      mode: 770
      
  - name: Copying token to worker nodes
    copy:
      src: "/{{inventory_dir}}/centos/{{ token_file }}"
      dest: /data/centos/join_token
    delegate_to: localhost

  - name: Joining worker nodes with kubernetes master
    shell: |
     kubeadm reset -f
     cat /data/centos/join_token | tail -2 > out.sh
     sh out.sh
